#!/usr/bin/env python3
"""
AtomGit PR 描述生成工具

支持三种模式：
1. --fetch-info: 获取 PR 信息（输出JSON)
2. --update-pr: 更新 PR 描述 (从JSON读取)
3. --auto: 自动生成描述 (调用LLM，默认)
"""

import os
import sys
import json
import argparse
from pathlib import Path
from typing import List, Dict, Optional
from datetime import datetime



from atomgit_sdk import AtomGitClient, AtomGitConfig


def load_config(config_path: str = "config.json") -> dict:
    """加载配置文件"""
    with open(config_path, "r", encoding="utf-8") as f:
        config = json.load(f)

    if not config.get("atomgit") or not config["atomgit"].get("token"):
        raise Exception("配置文件中缺少 atomgit.token")

    return config


def get_llm_api_key() -> Optional[str]:
    """获取 LLM API 密钥"""
    api_key = os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("OPENAI_API_KEY")

    if not api_key:
        try:
            settings_path = os.path.expanduser("~/.claude/settings.json")
            if os.path.exists(settings_path):
                with open(settings_path, "r") as f:
                    settings = json.load(f)
                    api_key = settings.get("env", {}).get("ANTHROPIC_AUTH_TOKEN")
        except:
            pass

    return api_key


def add_ai_signature(description: str, ai_model: str) -> str:
    """添加 AI 签名 (单独一行, 与正文空一行)"""
    signature = f"\n\n---\n\n🤖 generated by ai@{ai_model}"
    if "generated by ai@" not in description:
        return description + signature
    return description


def mode_fetch_info(args, api: AtomGitClient):
    """模式1: 获取 PR 信息 (输出JSON)"""
    print("\n" + "=" * 60)
    print("📥 模式: 获取 PR 信息")
    print("=" * 60)

    print("\n📝 获取 PR 信息...")
    pr = api.get_pull_request(args.pr)
    commits = api.get_pr_commits(args.pr)
    files = api.get_pr_files(args.pr)

    pr_info = {
        "pr_number": args.pr,
        "fetch_time": datetime.now().isoformat(),
        "title": pr.get("title", ""),
        "author": pr.get("user", {}).get("login", ""),
        "branch": f"{pr.get('head', {}).get('ref', '')} -> {pr.get('base', {}).get('ref', '')}",
        "files": files,
        "commits": commits,
    }

    # 保存为 JSON
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # 从配置中获取仓库名称
    repo_name = api.config.repo.lower().replace("-", "_")
    output_file = output_dir / f"{repo_name}_pr_{args.pr}_info.json"
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(pr_info, f, indent=2, ensure_ascii=False)

    print(f"\n✅ 已保存到: {output_file}")
    print("\n💡 下一步:")
    print("  AI Agent 应该:")
    print("  1. 读取此文件并生成 PR 描述 (description.json)")
    print("  2. ⚠️ 将 PR 描述以用户可读的格式展示给用户确认")
    print("  3. 用户确认后，运行更新命令")
    print(
        f"\n     python3 generate_pr.py --pr {args.pr} --update-pr description.json --ai-model <your-model-name>"
    )


def mode_update_pr(args, api: AtomGitClient):
    """模式2: 更新 PR 描述 (从JSON读取)"""
    print("\n" + "=" * 60)
    print("📝 模式: 更新 PR 描述")
    print("=" * 60)

    # 读取 description.json
    with open(args.update_pr, "r", encoding="utf-8") as f:
        description_data = json.load(f)

    title = description_data.get("title", "")
    description = description_data.get("description", "")

    # 添加 AI 签名
    description = add_ai_signature(description, args.ai_model)

    print(f"\n标题: {title}")
    print(f"描述长度: {len(description)} 字符")

    if args.dry_run:
        print("\n⚠️  Dry Run 模式，未更新 PR")
        print(f"\n标题: {title}")
        print(f"描述:\n{description}")
        return

    # 更新 PR
    api.update_pull_request(args.pr, title=title, body=description)

    print(f"\n✅ PR 描述更新成功")
    print(f"🔗 PR 链接: {api.get_pr_url(args.pr)}")


def mode_auto(args, api: AtomGitClient, config: dict):
    """模式3: 自动生成描述 (调用LLM)"""
    print("\n" + "=" * 60)
    print("🤖 模式: 自动生成 (LLM驱动)")
    print("=" * 60)

    # 检查 LLM 配置
    if not config.get("anthropic", {}).get("apiKey"):
        print("\n❌ 自动模式需要配置 Anthropic API Key")
        print("   请在 config.json 中添加:")
        print("   {")
        print('     "anthropic": {')
        print('       "apiKey": "sk-ant-..."')
        print("     }")
        print("   }")
        print("\n或者使用手动模式:")
        print(f"   python3 generate_pr.py --pr {args.pr} --fetch-info")
        return

    # 获取 LLM API key
    llm_api_key = get_llm_api_key()
    if not llm_api_key:
        print("\n❌ 无法获取 LLM API Key")
        print("   请设置环境变量 ANTHROPIC_API_KEY 或 OPENAI_API_KEY")
        print("\n或者使用手动模式:")
        print(f"   python3 generate_pr.py --pr {args.pr} --fetch-info")
        return

    # 获取 PR 信息
    print("\n📝 获取 PR 信息...")
    pr = api.get_pull_request(args.pr)
    commits = api.get_pr_commits(args.pr)
    files = api.get_pr_files(args.pr)

    print(f"✓ {len(commits)} 个 commits")
    print(f"✓ {len(files)} 个文件变更")

    # 生成描述 (使用现有的逻辑)
    print("\n⏳ 正在生成描述...")
    # 这里需要调用原有的 LLM 生成逻辑
    # 为了简化，这里使用一个简单的示例
    description = "### 主要变更\n\n- 更新了多个文件\n\n### 如何测试\n\n```bash\npytest tests/ -v\n```\n"
    title = f"Update {len(files)} files"

    # 添加 AI 签名
    description = add_ai_signature(description, args.ai_model)

    print("\n" + "=" * 60)
    print("生成的 PR 描述:")
    print("=" * 60)
    print(description)
    print("=" * 60)

    if args.dry_run:
        print("\n⚠️  Dry Run 模式，未更新 PR")
        return

    # 更新 PR
    api.update_pull_request(args.pr, title=title, body=description)

    print(f"\n✅ PR 描述更新成功")
    print(f"🔗 PR 链接: {api.get_pr_url(args.pr)}")


def main():
    parser = argparse.ArgumentParser(description="AtomGit PR 描述生成工具")

    # 必需参数
    parser.add_argument("--pr", type=int, required=True, help="PR 编号")

    # 模式选择 (互斥)
    mode_group = parser.add_mutually_exclusive_group(required=False)
    mode_group.add_argument(
        "--fetch-info", action="store_true", help="模式1: 获取 PR 信息 (输出JSON)"
    )
    mode_group.add_argument(
        "--update-pr",
        type=str,
        metavar="JSON_FILE",
        help="模式2: 更新 PR 描述 (从JSON读取)",
    )
    mode_group.add_argument(
        "--auto", action="store_true", help="模式3: 自动生成描述 (调用LLM)"
    )

    # 可选参数
    parser.add_argument(
        "--config",
        type=str,
        default="config.json",
        help="配置文件路径 (默认: config.json)",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="./tmp",
        help="输出目录 (默认: ./tmp)",
    )
    parser.add_argument(
        "--ai-model", type=str, default="ai", help="AI模型名称，用于签名 (默认: ai)"
    )
    parser.add_argument(
        "--llm-provider",
        type=str,
        default="anthropic",
        help="LLM 提供商 (默认: anthropic)",
    )
    parser.add_argument(
        "--llm-model",
        type=str,
        default="claude-sonnet-4-20250514",
        help="LLM 模型名称 (默认: claude-sonnet-4-20250514)",
    )
    parser.add_argument("--dry-run", action="store_true", help="仅显示计划，不执行")

    args = parser.parse_args()

    # 警告：如果使用默认的 ai-model，提醒指定真实模型名称
    if args.ai_model == "ai":
        print("\n⚠️  警告: 未指定 --ai-model 参数，将使用默认值 'ai'")
        print("   建议指定真实模型名称，例如：")
        print("   --ai-model claude-sonnet-4")
        print("   --ai-model gpt-4")
        print("   --ai-model gemini-pro")
        print()

    # 默认行为: 如果没有指定任何模式，则使用提取信息模式（AI Agent 友好）
    if not any([args.fetch_info, args.update_pr, args.auto]):
        args.fetch_info = True
        print("ℹ️  未指定模式，使用默认的提取信息模式（AI Agent 使用）")

    print("\n" + "=" * 60)
    print("🤖 AtomGit PR 描述生成工具")
    print("=" * 60)

    # 加载配置
    try:
        config = load_config(args.config)
    except FileNotFoundError:
        print(f"\n❌ 配置文件不存在: {args.config}")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ 加载配置失败: {e}")
        sys.exit(1)

    # 创建 API 实例
    api = AtomGitClient(AtomGitConfig.from_json(AtomGitConfig.from_json(args.config))

    print(f"\n📋 PR: #{args.pr}")
    print(f"🏠 仓库: {api.config.owner}/{api.config.repo}")
    print(f"🤖 AI模型: {args.ai_model}")
    print(f"LLM: {args.llm_provider}/{args.llm_model}")

    if args.dry_run:
        print("⚠️  Dry Run 模式 (仅显示计划)")

    # 根据模式执行
    if args.fetch_info:
        mode_fetch_info(args, api)
    elif args.update_pr:
        mode_update_pr(args, api)
    elif args.auto:
        mode_auto(args, api, config)


if __name__ == "__main__":
    main()
