# Task: Put pencil into a box using 2 arms
# Robot: so101
# Cameras: top, leftwrist, rightwrist

robot_interface:
  ros__parameters:
    is_mock: false
    robot_ids: [so101_follower_1, so101_follower_2]
    so101_follower_1:
      type: so101_follower
      port: /dev/ttyACM0
      camera_names: [top, leftwrist, rightwrist]
      cameras:
        top:
          index: 0
          width: 640
          height: 480
          fps: 30
        leftwrist:
          index: 2
          width: 640
          height: 480
          fps: 30
        rightwrist:
          index: 4
          width: 640
          height: 480
          fps: 30
      
    so101_follower_2:
      type: so101_follower
      port: /dev/ttyACM1
