"""
评论格式化器
负责将代码问题格式化为 AtomGit PR 评论
"""

from typing import Dict, List, Optional
from atomgit_sdk import CodeIssue


# 官方参考资料
OFFICIAL_REFERENCES = {
    "syntax_error": [
        {"title": "Python Official Documentation", "url": "https://docs.python.org/3/"},
    ],
    "bug": [
        {
            "title": "Python Debugging Guide",
            "url": "https://docs.python.org/3/library/debug.html",
        },
    ],
    "security": [
        {"title": "OWASP Top 10", "url": "https://owasp.org/www-project-top-ten/"},
        {
            "title": "Python Security Best Practices",
            "url": "https://python.readthedocs.io/en/stable/library/security_warnings.html",
        },
    ],
    "logic_error": [
        {
            "title": "Python Control Flow",
            "url": "https://docs.python.org/3/tutorial/controlflow.html",
        },
    ],
    "api_misuse": [
        {
            "title": "Python Standard Library",
            "url": "https://docs.python.org/3/library/",
        },
    ],
    "error_handling": [
        {
            "title": "Python Exceptions",
            "url": "https://docs.python.org/3/tutorial/errors.html",
        },
    ],
    "performance": [
        {
            "title": "Python Performance Tips",
            "url": "https://wiki.python.org/moin/PythonSpeed/PerformanceTips",
        },
    ],
}


class CommentFormatter:
    """评论格式化器"""

    def __init__(self, confidence_threshold: int = 80, ai_model: str = "ai"):
        self.confidence_threshold = confidence_threshold
        self.ai_model = ai_model
        self.ai_signature = f"\n\n---\n🤖 generated by ai@{self.ai_model}"

    def get_severity_icon(self, severity: str) -> str:
        """获取严重程度图标"""
        icons = {
            "critical": "🚨",
            "error": "❌",
            "warning": "⚠️",
            "suggestion": "💡",
            "info": "ℹ️",
        }
        return icons.get(severity, "📝")

    def get_type_name(self, issue_type: str) -> str:
        """获取问题类型中文名"""
        names = {
            "syntax_error": "语法错误",
            "bug": "Bug",
            "security": "安全问题",
            "logic_error": "逻辑错误",
            "api_misuse": "API 误用",
            "error_handling": "错误处理",
            "performance": "性能问题",
        }
        return names.get(issue_type, issue_type)

    def add_references(self, body: str, issue_type: str) -> str:
        """添加官方参考资料"""
        refs = OFFICIAL_REFERENCES.get(issue_type, [])

        if not refs:
            return body

        body += "\n**官方参考资料**:\n"
        for ref in refs:
            body += f"- [{ref['title']}]({ref['url']})\n"

        return body

    def format_issue(
        self, issue: CodeIssue, position: Optional[int] = None
    ) -> Optional[dict]:
        """格式化单个问题为行内评论"""
        if issue.confidence < self.confidence_threshold:
            return None

        body = ""

        icon = self.get_severity_icon(issue.severity)

        body += f"{icon} **{issue.title}**\n\n"

        if issue.description:
            body += f"{issue.description}\n\n"

        if issue.context_code:
            body += f"**上下文代码**:\n```\n{issue.context_code}\n```\n\n"

        if issue.fix_code:
            body += f"**修复方案**:\n```\n{issue.fix_code}\n```\n\n"
            if issue.fix_explanation:
                body += f"{issue.fix_explanation}\n\n"

        body = self.add_references(body, issue.type)

        body += self.ai_signature

        result = {"path": issue.file, "body": body, "line": issue.line}

        if position is not None:
            result["position"] = position

        return result

    def format_issues(
        self,
        issues: List[CodeIssue],
        positions: Optional[Dict[str, Dict[int, int]]] = None,
    ) -> List[dict]:
        """格式化问题列表"""
        if positions is None:
            positions = {}

        comments = []
        for issue in issues:
            formatted = self.format_issue(issue)
            if formatted:
                file_positions = positions.get(issue.file, {})
                position = file_positions.get(issue.line)
                if position is not None:
                    formatted["position"] = position
                comments.append(formatted)

        return comments

    def format_summary(
        self, issues: List[CodeIssue], pr_number: int, pr_title: str
    ) -> str:
        """格式化代码审查总结"""
        if not issues:
            return (
                "## 代码审查完成\n\n✅ 未发现问题。代码变更质量良好。"
                + self.ai_signature
            )

        filtered_issues = [
            i for i in issues if i.confidence >= self.confidence_threshold
        ]

        if not filtered_issues:
            return (
                f"## 代码审查完成\n\n✅ 发现 {len(issues)} 个潜在问题，但置信度均低于阈值 ({self.confidence_threshold})。"
                + self.ai_signature
            )

        by_type = {}
        for issue in filtered_issues:
            issue_type = issue.type
            if issue_type not in by_type:
                by_type[issue_type] = []
            by_type[issue_type].append(issue)

        body = "## 代码审查摘要\n\n"
        body += f"- **PR**: #{pr_number} - {pr_title}\n"
        body += f"- **问题数**: {len(filtered_issues)}\n\n"

        for issue_type, type_issues in by_type.items():
            type_name = self.get_type_name(issue_type)
            body += f"### {type_name}\n\n"

            for issue in type_issues:
                icon = self.get_severity_icon(issue.severity)
                body += f"- {icon} `{issue.file}:{issue.line}` - {issue.title}\n"

            body += "\n"

        body += "详细问题请查看各代码行的行内评论。\n"
        body += self.ai_signature

        return body

    def deduplicate(self, issues: List[CodeIssue]) -> List[CodeIssue]:
        """去重"""
        seen = set()
        unique = []
        for issue in issues:
            key = (issue.file, issue.line, issue.title)
            if key not in seen:
                seen.add(key)
                unique.append(issue)
        return unique
