"""
评论格式化器
负责将架构问题格式化为 AtomGit PR 评论
"""

from typing import Dict, List, Optional
from atomgit_sdk import ArchitectureIssue


# IB-Robot 架构参考资料
ARCHITECTURE_REFERENCES = {
    "ssot": [
        {
            "title": "Single Source of Truth Pattern",
            "url": "https://deepwiki.com/wuxiaoqiang12/IB_Robot/3.1-single-source-of-truth-pattern",
        },
        {
            "title": "Configuration System",
            "url": "https://deepwiki.com/wuxiaoqiang12/IB_Robot/5-configuration-system-(robot_config)",
        },
    ],
    "contract": [
        {
            "title": "Contract System",
            "url": "https://deepwiki.com/wuxiaoqiang12/IB_Robot/3.2-contract-system",
        },
        {
            "title": "Contract Builder",
            "url": "https://deepwiki.com/wuxiaoqiang12/IB_Robot/5.2-contract-builder",
        },
    ],
    "control_mode": [
        {
            "title": "Control Mode Architecture",
            "url": "https://deepwiki.com/wuxiaoqiang12/IB_Robot/3.3-control-mode-architecture",
        },
        {
            "title": "Launch System",
            "url": "https://deepwiki.com/wuxiaoqiang12/IB_Robot/5.3-launch-builders",
        },
    ],
    "tensormsg": [
        {
            "title": "tensormsg Protocol",
            "url": "https://deepwiki.com/wuxiaoqiang12/IB_Robot/6-tensormsg-protocol",
        }
    ],
    "inference": [
        {
            "title": "Inference Pipeline",
            "url": "https://deepwiki.com/wuxiaoqiang12/IB_Robot/7-inference-pipeline",
        }
    ],
    "action_dispatch": [
        {
            "title": "Action Dispatch",
            "url": "https://deepwiki.com/wuxiaoqiang12/IB_Robot/8-action-dispatch",
        }
    ],
    "ros2": [
        {
            "title": "ROS 2 Humble Documentation",
            "url": "https://docs.ros.org/en/humble/",
        }
    ],
    "python": [
        {
            "title": "Python Best Practices",
            "url": "https://docs.python.org/3/tutorial/index.html",
        }
    ],
}


class CommentFormatter:
    """评论格式化器"""

    def __init__(self, ai_model: str = "ai"):
        self.ai_model = ai_model
        self.ai_signature = f"\n\n---\n🤖 generated by ai@{self.ai_model}"

    def get_severity_icon(self, severity: str) -> str:
        """获取严重程度图标"""
        icons = {
            "critical": "🚨",
            "error": "❌",
            "warning": "⚠️",
            "suggestion": "💡",
            "info": "ℹ️",
        }
        return icons.get(severity, "📝")

    def get_pillar_name(self, pillar: str) -> str:
        """获取架构支柱中文名"""
        names = {
            "ssot": "配置驱动 (Spec-Driven)",
            "contract": "契约系统 (Contract)",
            "control_mode": "控制模式 (Control Mode)",
            "tensormsg": "协议转换 (tensormsg)",
            "inference": "推理服务 (Inference)",
            "action_dispatch": "动作执行 (Action Dispatch)",
            "ros2": "ROS 2 原生性",
            "python": "Python 规范",
        }
        return names.get(pillar, pillar)

    def add_references(self, body: str, pillar: str) -> str:
        """添加架构参考资料"""
        refs = ARCHITECTURE_REFERENCES.get(pillar, [])

        if not refs:
            return body

        body += "\n**架构参考资料**:\n"
        for ref in refs:
            body += f"- [{ref['title']}]({ref['url']})\n"

        return body

    def format_issue(
        self, issue: ArchitectureIssue, position: Optional[int] = None
    ) -> dict:
        """格式化单个问题为行内评论"""
        body = ""

        # 严重程度图标
        icon = self.get_severity_icon(issue.severity)
        pillar_name = self.get_pillar_name(issue.pillar)

        # 标题
        body += f"{icon} **架构违背: {issue.title}**\n\n"
        body += f"**架构支柱**: {pillar_name}\n\n"

        # 描述
        if issue.description:
            body += f"**问题**: {issue.description}\n\n"

        # 上下文代码
        if issue.context_code:
            body += f"**上下文代码**:\n```\n{issue.context_code}\n```\n\n"

        # 修复方案
        if issue.fix:
            body += f"**修改方案**: {issue.fix}\n\n"

        # 添加参考资料
        body = self.add_references(body, issue.pillar)

        # 添加 AI 签名
        body += self.ai_signature

        result = {"path": issue.file, "body": body, "line": issue.line}

        if position is not None:
            result["position"] = position

        return result

    def format_issues(
        self,
        issues: List[ArchitectureIssue],
        positions: Dict[str, Dict[int, int]] = None,
    ) -> List[dict]:
        """格式化问题列表"""
        if positions is None:
            positions = {}

        comments = []
        for issue in issues:
            file_positions = positions.get(issue.file, {})
            position = file_positions.get(issue.line)
            comments.append(self.format_issue(issue, position))

        return comments

    def format_pr_level_issue(self, issue: ArchitectureIssue) -> str:
        """格式化单个问题为 PR 级评论（非变更文件使用）"""
        icon = self.get_severity_icon(issue.severity)
        pillar_name = self.get_pillar_name(issue.pillar)

        body = f"**{icon} {issue.title}**\n\n"
        body += f"**文件**: `{issue.file}`\n"
        body += f"**严重性**: {issue.severity}\n"
        body += f"**架构支柱**: {pillar_name}\n\n"
        if issue.description:
            body += f"{issue.description}\n\n"
        if issue.fix:
            body += f"**修改方案**: {issue.fix}\n\n"

        body = self.add_references(body, issue.pillar)
        body += self.ai_signature
        return body

    def format_pr_level_issues(self, issues: List[ArchitectureIssue]) -> str:
        """格式化多个问题为一条 PR 级评论"""
        parts = []
        for issue in issues:
            parts.append(self.format_pr_level_issue(issue))
        return "\n\n---\n\n".join(parts)

    def format_summary(self, issues: List[ArchitectureIssue]) -> str:
        """格式化架构审查总结"""
        if not issues:
            return (
                "## 架构审查完成\n\n✅ 未发现架构违背问题。代码变更符合 IB_Robot 架构原则。"
                + self.ai_signature
            )

        # 按支柱分组
        by_pillar = {}
        for issue in issues:
            pillar = issue.pillar
            if pillar not in by_pillar:
                by_pillar[pillar] = []
            by_pillar[pillar].append(issue)

        body = "## 架构审查报告\n\n"
        body += f"发现 **{len(issues)}** 个架构相关问题：\n\n"

        for pillar, pillar_issues in by_pillar.items():
            pillar_name = self.get_pillar_name(pillar)
            body += f"### {pillar_name}\n\n"

            for issue in pillar_issues:
                icon = self.get_severity_icon(issue.severity)
                body += f"- {icon} [{issue.file}:{issue.line}](#{issue.file.replace('/', '-')}-L{issue.line}) {issue.title}\n"

            body += "\n"

        # 添加参考资料
        body += "---\n\n**架构文档**: [DeepWiki - IB_Robot](https://deepwiki.com/wuxiaoqiang12/IB_Robot)\n"
        body += self.ai_signature

        return body
